version: '3.3'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: heroes
      MYSQL_USER: user
      MYSQL_PASSWORD: password

